apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: winterfall-worker
  namespace: winterfall
spec:
  schedule: "* 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: winterfall-worker
              image: eklhad/winterfall-worker:0.1
              imagePullPolicy: Always
              ports:
                - containerPort: 80
                  protocol: TCP
              env:
                - name: PG_DB_ADDR
                  valueFrom:
                    secretKeyRef:
                      name: winterfall-pg-creds
                      key: PG_DB_ADDR
                - name: PG_DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: winterfall-pg-creds
                      key: PG_DB_NAME
                - name: PG_DB_UN
                  valueFrom:
                    secretKeyRef:
                      name: winterfall-pg-creds
                      key: PG_DB_UN
                - name: PG_DB_PW
                  valueFrom:
                    secretKeyRef:
                      name: winterfall-pg-creds
                      key: PG_DB_PW
          restartPolicy: OnFailure